# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(default='Description Placeholder', max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='short_description',
            field=models.CharField(default='Short Description Placeholder', max_length=200),
        ),
    ]
