# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171216_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='Step Description Placeholder', max_length=20000)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='youtube',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.Recipe'),
        ),
    ]
