# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171216_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='calories',
        ),
    ]
