# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_ingredient_calories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='is_vegetarian',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='picture',
        ),
    ]
