# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171216_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='amount',
        ),
    ]
