# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_recipe_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='minutes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='Recipe Name', max_length=200),
        ),
    ]
