# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20171216_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='location',
            field=models.ManyToManyField(related_name='location', to='core.Location'),
        ),
    ]
